### ISSUE TITLE
[TASK] 소셜 로그인 구현

### ISSUE THREAD

**Issue by lxxmnmn** [DDD-Community/jsonWeb-front#15]
## 요구사항
- [x] Kakao Developers 내 애플리케이션 등록
- [x] 세부사항(동의항목, Redirect URI 등) 설정
- [ ] 로그인 컴포넌트 생성
- [ ] 받아온 인가코드를 백엔드에 넘기는 작업
- [ ] 백엔드에서 프로젝트 토큰을 받아오는 작업
- [ ] _

## 기타
세부사항 설정 시 성흥님과 협의 必

**Comment by choipureum** [comment]
#2 에서 이슈트래킹하도록 하겠습니다
