### ISSUE TITLE
[TASK] login 구현

### ISSUE THREAD

**Issue by choipureum** [DDD-Community/jsonWeb-front#2]
## 💡 개요
- 로그인 구현

## 📑 작업 사항
- [x] Kakao Developers 내 애플리케이션 등록
- [x] 세부사항(동의항목, Redirect URI 등) 설정
- [x] 로그인 모달 UI 구현 >>  `페이지 UI로 수정`
- [x] 카카오에서 인가코드를 받아와 서버에 보내기
- [x] 서버에서 JWT 받아오기

## 기타
세부사항 설정 시 성흥님과 협의 必
 
## 🔎 기타
서브 - @jmpark-dev

**Comment by lxxmnmn** [comment]
컨플릭트 날까봐 #29 머지되면 pr 올리겠습니다

**Comment by choipureum** [comment]
> 컨플릭트 날까봐 #29 메인페이지 머지되면 pr 올리겠습니다

merge 막혀있어서 그냥 올려도 될거같습니다😃
