### ISSUE TITLE
[TASK] 인증 작성 페이지 UI 구현

### ISSUE THREAD

**Issue by lxxmnmn** [DDD-Community/jsonWeb-front#42]
## 요구사항

상세페이지에서 접근 가능한 페이지 먼저 작업

**Comment by choipureum** [comment]
![image](https://user-images.githubusercontent.com/55127127/209639279-24c7fcd7-5016-4b60-b144-bbd3238a8f4b.png)

요부분 `components/blocks/SelectBox` 컴포넌트 사용하면 됩니다. 사용 할때 말해주면 조금 리팩토링 손봐드리겟습니다 😉
